spring.application.name=ticket-service
server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_db
spring.datasource.username=postgres
spring.datasource.password=RealMadrid9*
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql